version: '3.7'

services: 
    api:
        image: 'coffeeshop-springboot-postgres:latest'
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: coffeeshop
        depends_on: 
            - db
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cafe
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=123456
            - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    db:
        image: 'postgres:13.1-alpine'
        ports:
            - "5432:5432"
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=cafe